// <auto-generated />
namespace TrainersManagerAssignment.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class DummySeed : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DummySeed));
        
        string IMigrationMetadata.Id
        {
            get { return "202102182243363_DummySeed"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
